from pathlib import Path
from decimal import Decimal
import json,hashlib,csv,io,sys,subprocess,datetime
R=Path('/Users/lyuhongwang/Developer/SEC_metrics');sys.path.insert(0,str(R/'scripts'))
from vnext.canonical import content_hash
from vnext.r5_b06_publication import _code_identity
F=Path('/Users/lyuhongwang/Documents/Codex/2026-09-11/r5-b06-followup');O=Path(__file__).parent
read=lambda p:json.loads(p.read_text());sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();prep=read(F/'complete/prepared.json');b=F/'complete/outputs/publications'/prep['publication_id'];m=read(b/'publication_manifest.json');body={k:v for k,v in m.items() if k not in ['record_type','publication_id']};assert 'publication_'+content_hash(value=body)[7:]==m['publication_id']==prep['publication_id'];assert sha(b/'publication_manifest.json')==prep['manifest_sha256']
files={f['path']:f for f in m['files']};checked=[]
def bound(path):
 p=b/path;assert p.stat().st_size==files[path]['size'] and sha(p)==files[path]['sha256'];checked.append({'path':path,**{k:files[path][k] for k in ['size','sha256']}});return p
meta=read(bound('internal/r5_primary.json'));adoption=read(bound('internal/r5_adoption.json'));batch=read(bound('internal/annual_complete_version.json'));matrix=list(csv.DictReader(io.StringIO(bound('metrics_matrix.csv').read_text())));evidence=list(csv.DictReader(io.StringIO(bound('metric_evidence.csv').read_text())))
assert meta==prep['code'];assert adoption['coverage']==prep['coverage'];assert content_hash(value={k:v for k,v in adoption.items() if k!='adoption_receipt_id'})==adoption['adoption_receipt_id']==m['annual_adoption_receipt_id'];assert content_hash(value={k:v for k,v in batch.items() if k!='batch_manifest_id'})==batch['batch_manifest_id']==m['batch_manifest_id']
assert meta['implementation_head']=='ce478c3c51feca89160e1996653c7d11a5463348';assert _code_identity(meta['implementation_head'])==meta['implementation_tree'];assert meta['policy']['production_authorized'] is False and adoption['formal_adoption'] is False and m['candidate_status']=='BLOCKED'
cmd=read(F/'complete-command.json');assert cmd['head']==cmd['head_after']==meta['implementation_head'] and cmd['exit_code']==0 and sha(Path(cmd['log']))==cmd['log_sha256'];assert len(matrix)==328 and len({(r['company'],r['metric_id']) for r in matrix})==328 and len(batch['cumulative_result_bindings'])==250 and batch['inherited_result_count']==240 and batch['selected_result_count']==10
pred=b/'internal/predecessor'/m['previous_publication_id'];assert sha(pred/'publication_manifest.json')==meta['predecessor_manifest_sha256'];old_matrix=list(csv.DictReader(io.StringIO((pred/'metrics_matrix.csv').read_text())));old_ev=list(csv.DictReader(io.StringIO((pred/'metric_evidence.csv').read_text())));unselected=lambda rows:[r for r in rows if r['metric_id']!='B06'];assert unselected(matrix)==unselected(old_matrix) and len(unselected(matrix))==318 and unselected(evidence)==unselected(old_ev)
rawreview=read(O/'raw-fact-index.json');sourcehashes={c['source_sha256'] for c in rawreview['companies']};summaries=[]
for c in adoption['coverage']:
 cid=c['company_id'];runbase='internal/annual_snapshot/runs/'+cid;mp=bound(runbase+'/manifest.json');rm=read(mp);rp=bound(runbase+'/records.jsonl');records=[json.loads(s) for s in rp.read_text().splitlines()];results=[r for r in records if r['record_type']=='METRIC_RESULT'];assert results==[c['result']]
 refs={r['source_reference_id']:r for r in records if r['record_type']=='SOURCE_REFERENCE'};obs=[r for r in records if r['record_type']=='VERIFIED_OBSERVATION'];trace=next(r for r in records if r['record_type']=='EXECUTION_TRACE');public=next(r for r in matrix if r['company']==c['company'] and r['metric_id']=='B06');assert public['status']==c['public_status'] and public['period_end']==c['actual_period']['period_end'];assert c['production_permission'] is False
 if cid=='southwest_airlines':assert Decimal(c['debt'])==Decimal('4901000000') and Decimal(c['result']['value'])==Decimal(4901)/Decimal(7981) and c['content_status']=='CONTENT_COMPLETE' and c['amendment_impact'][0]['decision']=='NO_B06_SOURCE_IMPACT' and len(obs)==3
 if cid=='lumen_technologies':assert c['debt']=='17441000000' and c['equity']=='-1117000000' and public['status']=='NOT_MEANINGFUL' and c['content_status']=='CONTENT_COMPLETE' and c['result']['value'] is None and len(obs)==4
 if cid in ['southwest_airlines','lumen_technologies']:
  rec=c['measurement_reconciliation']; assert all(any(o['source_binding'].get('fact_id')==f['fact_id'] and o['value']==f['value'] and all(o['source_binding'].get(k)==v for k,v in f['source_binding'].items()) for o in obs) for f in rec['calculation_facts'])
  for o in obs:
   sb=o['source_binding'];assert sb['source_reference_id'] in refs
   if 'xbrl_fact_ordinal' in sb:assert refs[sb['source_reference_id']]['source_role']=='accession_xbrl'
 if cid in ['ford_motor_company','pfizer','jpmorgan_chase','salesforce','macys']:
  ass=c['source_composition_evidence']['assessments'];assert c['content_status']=='CONTENT_GAPS_REMAIN' and public['status']=='NEEDS_REVIEW' and not public['value'] and len(ass)==1 and ass[0]['source_sha256'] in sourcehashes and ass[0]['remaining_business_decision'] and ass[0]['not_a_calculation_input']
  questions=[a['remaining_business_decision'] for a in ass]
 else:questions=[]
 summaries.append({'company_id':cid,'status':c['public_status'],'debt_candidate':c['debt'],'equity':c['equity'],'value':c['result']['value'],'content_status':c['content_status'],'blockers':c['blockers'],'remaining_decisions':questions,'run_id':rm['run_id'],'result_id':c['result']['result_id']})
statuscounts={s:sum(c['public_status']==s for c in adoption['coverage']) for s in ['OK','NOT_MEANINGFUL','NEEDS_REVIEW']};assert statuscounts=={'OK':3,'NOT_MEANINGFUL':2,'NEEDS_REVIEW':5}
result={'status':'PASS_BOUNDED_FINAL_PACKAGE_EVIDENCE_REVIEW','reviewer':'independent Codex model subtask /root/debt_reconciliation_review; not human approval','time':datetime.datetime.now(datetime.timezone.utc).isoformat(),'implementation_head':meta['implementation_head'],'implementation_tree':meta['implementation_tree'],'publication_id':m['publication_id'],'manifest_file_sha256':sha(b/'publication_manifest.json'),'adoption_receipt_object_id':adoption['adoption_receipt_id'],'batch_object_id':batch['batch_manifest_id'],'personally_executed':['Recompute publication/adoption/batch content IDs; manifest byte hash; selected25 packagefile byte hashes','Crosscheck approved code Git-object implementation identity against package and actual prepare command record/log SHA','Compare coverage to all10 stored native result records and public matrix periods/status','Crosscheck SW carrying computation and Lumen evaluated-null against independently audited original sources and new native observation source roles','Confirm five remaining decisions preserved and explained from verified XML source identities','Compare all318 unselected public rows and corresponding evidence against actual embedded predecessor'],'read_execution_records':[{'path':'complete-command.json','exit_code':cmd['exit_code'],'head':cmd['head'],'log_sha256':cmd['log_sha256']}],'reused_prior_checks':['Independent original seven-source content review','Current-code final10 short tests','Prior3oldv1 full native graph reads','Prior3newtrial03 native graph reads; actual measurement runtime and spec bytes unchanged'],'not_executed':['Did not repeat full publication.verify_publication_bundle or replay all embedded predecessor directories','Did not repeat all new Run native graphs; package record/result checks are not fresh graph replay','Did not rerun material fault suite or production operations'],'coverage_status_counts':statuscounts,'coverage':summaries,'coordinate_count':250,'public_rows':328,'unchanged_public_rows':318,'production_authorized':False,'business_calls':[0,0,0],'checked_files':checked,'known_reporting_limits':['Ford .890bn and Macys .013bn coverage.debt are unaccepted lease subsets; actual established industrial/bond totals reside in source composition evidence','JPM carrying note fact is known from source; CARRYING_MEASUREMENT_NOT_ESTABLISHED means missing machine rule mapping, not absence of carrying disclosure']}
(O/'final-package-review.json').write_text(json.dumps(result,indent=2,ensure_ascii=False)+'\n');print(result['status'],statuscounts)
