from pathlib import Path
import json,csv,hashlib,subprocess
from vnext.canonical import content_hash
O=Path('/Users/lyuhongwang/Documents/Codex/2026-09-11/r5-b06-structured/independent-discovery');ROOT=Path('/Users/lyuhongwang/Developer/SEC_metrics');P=O.parent/'complete-final/outputs/publications/publication_fa51db0b563c0ea97c545a3edced42cdfdd9a21a1a7d6f341f140bbe28653e71';m=json.loads((P/'publication_manifest.json').read_bytes());manifest_sha=hashlib.sha256((P/'publication_manifest.json').read_bytes()).hexdigest();assert manifest_sha=='105eea0390a184278a9a3c70050885f6297abe2c68d3a31f749fda7397ab30f3';assert m['publication_id']=='publication_'+content_hash(value={k:v for k,v in m.items() if k not in {'publication_id','record_type'}})[7:]
actual={str(p.relative_to(P)) for p in P.rglob('*') if p.is_file()};assert actual=={x['path'] for x in m['files']}|{'publication_manifest.json'}
for f in m['files']:
 p=P/f['path'];assert not p.is_symlink();b=p.read_bytes();assert len(b)==f['size'] and hashlib.sha256(b).hexdigest()==f['sha256']
meta=json.loads((P/'internal/r5_primary.json').read_bytes());assert meta['implementation_head']=='f56d740b47ad433f0762862c73b6089c408d3f65'
expected_tree=content_hash(value=subprocess.check_output(['git','ls-tree','-r',meta['implementation_head'],'scripts','tools','config','catalog','requirements'],cwd=ROOT,text=True));assert expected_tree==meta['implementation_tree']
actual_active=json.loads((ROOT/'outputs/active_publication.json').read_bytes());assert actual_active['publication_id']==m['previous_publication_id']==meta['predecessor_publication_id'];assert actual_active['bundle_manifest_sha256']==meta['predecessor_manifest_sha256'];B=P/'internal/predecessor'/m['previous_publication_id'];assert (B/'publication_manifest.json').read_bytes()==(ROOT/'outputs/publications'/m['previous_publication_id']/'publication_manifest.json').read_bytes()
batch=json.loads((P/'internal/annual_complete_version.json').read_bytes());assert batch['batch_manifest_id']==content_hash(value={k:v for k,v in batch.items() if k!='batch_manifest_id'});assert len(batch['cumulative_result_bindings'])==250 and batch['inherited_result_count']==240 and batch['selected_result_count']==10
adoption=json.loads((P/'internal/r5_adoption.json').read_bytes());assert adoption['adoption_receipt_id']==content_hash(value={k:v for k,v in adoption.items() if k!='adoption_receipt_id'});assert adoption['batch_manifest_id']==batch['batch_manifest_id'];assert adoption['status']=='BLOCKED' and adoption['formal_adoption'] is False
rows=lambda p:list(csv.DictReader(p.open()));old=rows(B/'metrics_matrix.csv');new=rows(P/'metrics_matrix.csv');olde=rows(B/'metric_evidence.csv');newe=rows(P/'metric_evidence.csv');key=lambda x:(x['company'],x['metric_id']);unselected=lambda xs:[x for x in xs if x['metric_id']!='B06'];assert len(new)==328 and len(old)==327 and len(unselected(new))==318;assert unselected(new)==unselected(old) and unselected(newe)==unselected(olde);assert len({key(x) for x in new})==len(new);assert {key(x) for x in new}-{key(x) for x in old}=={('JPMorgan Chase','B06')}
prior={x['company_id']:x for x in json.loads((O/'actual-ten-company-content-review.json').read_text())['companies']};linked=[]
for bind in batch['cumulative_result_bindings']:
 if bind['metric_id']!='B06':continue
 cid=bind['company_id'];D=P/'internal/annual_snapshot'/bind['snapshot_run_path'];man=json.loads((D/'manifest.json').read_bytes());rec=[json.loads(x) for x in (D/'records.jsonl').read_text().splitlines()];res=next(x for x in rec if x['record_type']=='METRIC_RESULT');assert res==prior[cid]['native_result'];assert man['target_period']==prior[cid]['period'];assert man['status']=='FROZEN';sel=json.loads((D.parent/(cid+'-selection.json')).read_bytes());cf=next(s for s in man['source_references'] if s['source_role']=='companyfacts');assert cf['raw_asset_id']==prior[cid]['companyfacts_sha256'];public=next(x for x in new if x['metric_id']=='B06' and x['cik']==sel['input']['entity']);expected=prior[cid]['expected_public_candidate_value'];assert public['status']==prior[cid]['expected_public_status'];assert (not public['value']) if expected is None else (public['value']==expected)
 linked.append({'company_id':cid,'run_id':man['run_id'],'result_id':res['result_id'],'source_raw_asset_id':cf['raw_asset_id'],'native_result_equals_independently_verified_previous_run':True,'actual_public_value':public['value'],'actual_public_status':public['status'],'adoption_status':bind['adoption_status']})
assert m['candidate_status']=='BLOCKED' and m['publication_credit']=='NONE_ISOLATED_STRUCTURED_MIGRATION';assert meta['policy']['production_authorized'] is False;assert not (O.parent/'complete-final/outputs/active_publication.json').exists()
report={'status':'PASS_INDEPENDENT_PACKAGE_BYTES_AND_CONTENT_BINDINGS','reviewer':'independent Codex subtask /root/b06_source_audit','publication_id':m['publication_id'],'manifest_byte_sha256':manifest_sha,'implementation':meta['implementation_head'],'file_count':len(m['files']),'total_file_bytes':sum(x['size'] for x in m['files']),'file_set_and_all_bytes_sha256':'PASS','publication_and_batch_adoption_object_ids':'PASS','actual_predecessor':m['previous_publication_id'],'predecessor_manifest_byte_sha256':meta['predecessor_manifest_sha256'],'actual_formal_active_unchanged':True,'native_coordinates':250,'inherited_coordinates':240,'new_coordinates':10,'public_rows':328,'unselected_public_rows_exactly_preserved':318,'all_unselected_evidence_preserved':True,'candidate_status':'BLOCKED','production_authorized':False,'no_candidate_active_pointer':True,'native_links':linked,'not_executed':['No full native validator replay or predecessor native reconstruction; these parent material execution checks reviewed separately'],'business_calls':[0,0,0]};(O/'final-package-checks.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps({'status':report['status'],'report':str(O/'final-package-checks.json'),'sha256':hashlib.sha256((O/'final-package-checks.json').read_bytes()).hexdigest()}))
