import csv,hashlib,json,os,subprocess,sys,tempfile,time
from pathlib import Path
state=Path('/Users/lyuhongwang/.local/state/sec_metrics/issue47-development-evidence/bank-performance-jpm-20261009/state');source=json.loads((state/'company-task.json').read_text())['source_root'];out=Path(tempfile.mkdtemp(prefix='jpm-statement-structural-',dir='/Users/lyuhongwang/.local/state/sec_metrics/issue47-development-evidence'));ops=[]
def protect():return {str(p.relative_to(state)):hashlib.sha256(p.read_bytes()).hexdigest() for p in state.rglob('*') if p.is_file() and ('/results/' in str(p) or p.name in ('current-result.json','completed-check.json'))}
old=protect()
def invoke(name,args,forbid=False):
 code='import sys,json;from unittest.mock import patch;from tools.vnext_company import main\nfrom vnext import historical_statement_cases as case\na=case._filing_source.__code__;b=case._deterministic_metric_graph.__code__\n'
 code+='c=case.prepare_historical_statement_year_case.__code__\ndef guard(frame,event,arg):\n if event=="call" and (frame.f_code is a or frame.f_code is b'+(' or frame.f_code is c' if forbid else '')+'):raise AssertionError("Structural state must not select amounts, and repeat cannot prepare")\nsys.setprofile(guard)\n'
 code+='with patch("socket.socket.connect",side_effect=AssertionError("No network")):\n raise SystemExit(main(json.loads(sys.argv[1])))'
 started=time.monotonic();p=subprocess.run([sys.executable,'-c',code,json.dumps(args)],capture_output=True,text=True,env={**os.environ,'PYTHONPATH':'scripts:tools:.','PYTHONDONTWRITEBYTECODE':'1'});(out/(name+'.stdout')).write_text(p.stdout);(out/(name+'.stderr')).write_text(p.stderr);v=json.loads(p.stdout);ops.append({'name':name,'seconds':time.monotonic()-started,'exit_code':p.returncode,'status':v.get('status')});print(ops[-1],flush=True);assert p.returncode==0,(p.stdout,p.stderr);return v
args=['run','--company','jpmorgan_chase','--period','fiscal-years','--fiscal-year-start','2021','--fiscal-year-end','2025','--metric','B01','--metric','B02','--metric','B04','--metric','B05','--source-root',source,'--work-dir',str(state),'--output-dir',str(out/'runs')];first=invoke('first-structural-positions',args);assert all(m['status']=='CANDIDATE_READY' for m in first['metrics']);assert all(hashlib.sha256((state/n).read_bytes()).hexdigest()==sha for n,sha in old.items());before=protect();repeat=invoke('repeat-forbid-preparation',args,True);assert all(m['status']=='NO_SOURCE_CONTENT_CHANGE' and not m['calculation_performed'] for m in repeat['metrics']) and before==protect();view=invoke('independent-results',['results','--company','jpmorgan_chase','--state-root',str(state),'--output-root',str(out/'read')],True);assert before==protect();rows=list(csv.DictReader((out/'read/metrics_matrix.csv').open()));selected=[r for r in rows if r['metric_id'] in ['B01','B02','B04','B05']];assert len(selected)==20 and all(r['value']=='' and r['status']=='N_A_STRUCTURAL' and r['cik']=='19617' and r['period_start']==r['fiscal_year']+'-01-01' and r['period_end']==r['fiscal_year']+'-12-31' for r in selected)
Path('docs/evidence/issue47_statement_structural_consumer_20261010/actual-company.json').write_text(json.dumps({'actual_main':'f6ef7886','state_root':str(state),'output_root':str(out),'operations':ops,'positions':[{k:r[k] for k in ['metric_id','fiscal_year','value','unit','status','period_start','period_end','result_id']} for r in selected],'original_files':len(old),'all_files':len(before),'original_files_preserved':True,'amount_source_and_graph_calls':0,'repeat_preparation_calls':0,'existing_bank_metrics_not_recomputed':True,'na_is_frozen_trait_scope_not_absent_disclosure':True,'new_calls':[0,0,0]},indent=2)+'\n')
