"""Only two affected MacyFY2023 coordinates on the received range/main combination."""
import csv,hashlib,json,subprocess,sys,tempfile,time
from pathlib import Path
state=Path('/Users/lyuhongwang/.local/state/sec_metrics/issue47-development-evidence/statement-pilot-macys-20261009/state');source=json.load((state/'company-task.json').open())['source_root'];base=Path(tempfile.mkdtemp(prefix='macys-range-main-f51-',dir='/Users/lyuhongwang/.local/state/sec_metrics/issue47-development-evidence'))
args=['run','--company','macys','--period','fiscal-years','--fiscal-year-start','2023','--fiscal-year-end','2023','--metric','B01','--metric','B02','--source-root',source,'--work-dir',str(state),'--output-dir',str(base/'runs')]
def hashes():return {str(p.relative_to(state)):hashlib.sha256(p.read_bytes()).hexdigest() for p in state.rglob('*') if p.is_file()}
before=hashes();protected={k:h for k,h in before.items() if '/results/' in k or '/shared-inputs/' in k or k=='company-task.json' or (k.endswith(('current-result.json','completed-check.json')) and not any('/'+m+'/periods/FY2023/' in k for m in ['B01','B02']))}
def invoke(name,a,forbid=False):
 code='import sys,json\nfrom unittest.mock import patch\nfrom tools.vnext_company import main\n'
 if forbid:code+='from vnext import company_fiscal_range as ranges,historical_statement_cases as cases,calculator\nblocked={ranges.discover_fiscal_range.__code__,cases.prepare_historical_statement_year_case.__code__,calculator.calculate_metric.__code__,calculator.calculate_observation_metric.__code__}\ndef guard(frame,event,arg):\n if event=="call" and frame.f_code in blocked:raise AssertionError("Repeat/read must not discover or compute")\nsys.setprofile(guard)\n'
 code+='with patch("socket.socket.connect",side_effect=AssertionError("No network")):\n raise SystemExit(main(json.loads(sys.argv[1])))'
 t=time.monotonic();p=subprocess.run([sys.executable,'-B','-c',code,json.dumps(a)],capture_output=True,text=True);r={'name':name,'seconds':time.monotonic()-t,'exit_code':p.returncode,'arguments':a,'stdout':p.stdout,'stderr':p.stderr};(base/(name+'.json')).write_text(json.dumps(r,indent=2)+'\n');print(name,p.returncode,round(r['seconds'],3),flush=True);assert p.returncode in (0,2) and not p.stderr,r;return r,json.loads(p.stdout)
first,report=invoke('two-related-coordinate-transition',args);assert len(report['metrics'])==2 and all(m['calculation_performed'] for m in report['metrics']);assert all(hashes().get(k)==h for k,h in protected.items());post={k:h for k,h in hashes().items() if '/results/' in k or '/shared-inputs/' in k or k.endswith(('current-result.json','completed-check.json')) or k=='company-task.json'}
repeat,report=invoke('forbidden-range-case-calculator-repeat',args,True);assert [m['status'] for m in report['metrics']]==['NO_SOURCE_CONTENT_CHANGE','PREVIOUS_INPUT_WITHHELD'] and not any(m['calculation_performed'] for m in report['metrics']);assert all(hashes().get(k)==h for k,h in post.items())
read,view=invoke('independent-current-export',['results','--company','macys','--state-root',str(state),'--output-root',str(base/'read')],True);assert read['exit_code']==0;assert all(hashes().get(k)==h for k,h in post.items())
rows=list(csv.DictReader((base/'read/metrics_matrix.csv').open()));row=next(x for x in rows if x['metric_id']=='B01' and x['fiscal_year']=='2023');held=next(x for x in rows if x['metric_id']=='B02' and x['fiscal_year']=='2023');assert row['value']=='23866000000' and row['unit']=='USD' and row['period_start']=='2023-01-29' and row['period_end']=='2024-02-03' and row['result_id']=='sha256:77805235a0d19e2a7dde8d90850d96e555e92399f47a243b60ed3c4c98b2eeed';assert not held['value'] and held['status']=='WITHHELD';assert 'HISTORICAL_PAIRED_REVENUE_SCOPE_UNRESOLVED' in held['notes'];assert len(rows)==22
root=Path(held['record_root']);assessment=json.loads((root/'input-assessments.json').read_text());receipt={'code_commit':subprocess.check_output(['git','rev-parse','HEAD'],text=True).strip(),'has_uncommitted_changes':bool(subprocess.check_output(['git','status','--porcelain','--untracked-files=no'],text=True).strip()),'first':first,'repeat':repeat,'read':read,'row':row,'held':held,'assessment':assessment,'state_root':str(state),'output_root':str(base),'old_protected_files':len(protected),'final_protected_files':len(post),'other_coordinates_not_processed':True,'new_calls':[0,0,0]};Path('work/range-main/actual-company.json').write_text(json.dumps(receipt,indent=2)+'\n');print('PASS real mixed successful total and stable prior-scope withheld; old other periods intact',flush=True)
