from pathlib import Path
import json,csv,hashlib,re,xml.etree.ElementTree as E,datetime
R=Path('/Users/lyuhongwang/Developer/SEC_metrics');O=Path(__file__).parent
sha=lambda b:hashlib.sha256(b).hexdigest()
norm=lambda e:' '.join(' '.join(e.itertext()).split())
rows=list(csv.DictReader((R/'evidence/requests_log.csv').open()))
out={'reviewer':'independent Codex subtask /root/amendment_review; model review, not human approval','created_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'business_calls':[0,0,0],'scope':'Complete saved original and amendment XHTML parsed; all amendment sections and inline facts inventoried, explanatory scope and actual body checked. No native full Run/publication replay performed by this review.','decisions':[]}
for cik,cid in [(92380,'southwest_airlines'),(2041610,'paramount_skydance_paramount_global')]:
 sp=R/f'evidence/submissions/CIK{cik:010d}.json';sub=json.loads(sp.read_bytes());recent=sub['filings']['recent'];filings=[{k:v[i] for k,v in recent.items()} for i,f in enumerate(recent['form']) if f in ('10-K','10-K/A') and recent['reportDate'][i]=='2025-12-31'];orig=next(x for x in filings if x['form']=='10-K');amend=next(x for x in filings if x['form']=='10-K/A');docrecords=[];roots=[]
 for f in [orig,amend]:
  row=next(x for x in reversed(rows) if x['accession']==f['accessionNumber'] and x['document_name']==f['primaryDocument'] and x['status_code']=='200' and x['repo_relative_path'].startswith('evidence/request_attempts/'))
  raw=(R/row['repo_relative_path']).read_bytes();assert sha(raw)==row['content_sha256'];hdr=json.loads((R/row['headers_repo_relative_path']).read_bytes());d=E.fromstring(raw);roots.append(d);es=list(d.iter());facts=[{'element_index':i,'tag':e.tag,'attributes':e.attrib,'text':norm(e)} for i,e in enumerate(es) if e.tag.split('}')[-1] in ('nonNumeric','nonFraction')];identity=[x for x in facts if x['attributes'].get('name') in ['dei:EntityCentralIndexKey','dei:DocumentType','dei:DocumentPeriodEndDate','dei:AmendmentFlag']];assert next(x for x in identity if x['attributes']['name']=='dei:DocumentType')['text']==f['form'];assert int(next(x for x in identity if x['attributes']['name']=='dei:EntityCentralIndexKey')['text'])==cik
  text=norm(d);note_start=text.upper().find('EXPLANATORY NOTE');note_end=next((text.find(marker,note_start) for marker in ['CAUTIONARY NOTE CONCERNING','PART IV'] if text.find(marker,note_start)>=0),-1)
  headings=[{'element_index':i,'id':e.attrib.get('id'),'tag':e.tag,'text':norm(e)} for i,e in enumerate(es) if e.tag.split('}')[-1]=='div' and len(norm(e))<180 and re.match(r'^(?:PART\s+(?:III|IV)|Item\s+\d+\.|SIGNATURES)',norm(e),re.I)]
  rec={'form':f['form'],'filing':f,'source_path':str(R/row['repo_relative_path']),'sha256':sha(raw),'size_bytes':len(raw),'request_ledger_row':row,'headers_path':str(R/row['headers_repo_relative_path']),'headers_sha256':sha((R/row['headers_repo_relative_path']).read_bytes()),'identity':identity,'element_count':len(es),'inline_fact_count':len(facts),'non_dei_inline_fact_count':sum(not x['attributes']['name'].startswith('dei:') for x in facts),'non_dei_inline_facts':[x for x in facts if f['form']=='10-K/A' and not x['attributes']['name'].startswith('dei:')],'body_headings':headings}
  if f['form']=='10-K/A':
   rec['explanatory_note']=text[note_start:note_end].strip();rec['complete_normalized_text_sha256']=sha(text.encode()); (O/(cid+'-amendment-normalized.txt')).write_text(text);rec['normalization']='Derived complete DOM itertext, whitespace collapsed; original raw path and SHA remain authoritative.'
  docrecords.append(rec)
 # Exact original table with debt and current/noncurrent reconciliation, no response or old Result used.
 d=roots[0];parents={c:p for p in d.iter() for c in p};tables=[]
 for e in d.iter():
  if e.attrib.get('name')=='us-gaap:LongTermDebtAndCapitalLeaseObligationsIncludingCurrentMaturities':
   a=e
   while a.tag.split('}')[-1]!='table':a=parents[a]
   if norm(a) not in [x['text'] for x in tables]:tables.append({'selected_fact_id':e.attrib.get('id'),'element_index':list(d.iter()).index(a),'text':norm(a),'serialized_element_sha256':sha(E.tostring(a))})
 # Evidence claims refer to specific complete source objects, not to a runtime accession allowlist.
 decision={'company_id':cid,'metric_id':'B06','decision':'NO_CHANGE_TO_ORIGINAL_DEBT_EQUITY_DISCLOSURE','target_period_end':orig['reportDate'],'original':docrecords[0],'amendment':docrecords[1],'original_debt_tables':tables,'binding_check':'Same original/amendment CIK and report period, original ordinary 10-K identity and immutable request bytes; amendment later filed; original B06 sources remain as-filed.','source_metadata_inconsistency':'Both original amendments report dei:AmendmentFlag=false; preserve discrepancy. Explicit SEC submissions form, DocumentType=10-K/A and body Amendment No.1 establish amendment existence. False flag cannot delete amendment.','financial_scope_observed':'No us-gaap debt/equity inline facts in amendment; no PartII Item7/7A/8/9A replacement sections. Mere absence alone is not a no-impact proof.'}
 if cik==92380:
  decision.update({'reference_evidence':'Explanatory Note names original annual fiscal end December31,2025; same issuer and sole ordinary 10-K for that period in saved submissions. It does not explicitly state original accession or filing date; do not invent an exact textual citation.','changed_scope':'Exhibit3.2 hyperlink to corporate bylaws, PartIV Item15 exhibit index and fresh Section302 certifications. All actual body sections were inventoried; debt-related words in repeated exhibit descriptions do not mean debt values were restated.','additional_business_finding':'Original debt subtotal4919m precedes18m debt discount/issuance cost; book numerator4901m=current324m+noncurrent4577m. Old4919/7981 ratio is correctly calculated under old selected amount but not the new carrying-value rule; amendment no-impact does not settle measurement selection.'})
 else:
  text=norm(roots[1]);needle='No financial statements or supplemental data are filed with this Amendment.';assert needle in text
  decision.update({'reference_evidence':'Explanatory Note explicitly links original10-K filed February25,2026, matching sole ordinary filing0002041610-26-000011 and same report end; same issuer CIK2041610.','changed_scope':'PartIII Items10,11,12,13,14 governance/compensation/ownership/related-party/audit-fee disclosures; PartIV Item15 certification exhibits and signatures. No standalone restated financial statements.','explicit_financial_exclusion':text[text.index(needle):text.index(needle)+len(needle)+110]})
 out['decisions'].append(decision)
out['implementation_recommendation']={'preferred_minimal_shape':'A source-bound amendment impact evidence object evaluated during new adoption, separate from unchanged original as-filed Run. Bind original filing+period+CIK+full raw SHA, amendment filing+full raw SHA, all amendments discovered, metric/scope, complete body section evidence, independent-review object and rule version. Unknown changed bytes require new determination. Do not accept by company/accession alone.','supported_nonfinancial_explanation_types':['Exhibit-link correction with explicit unchanged-disclosure statement and complete body limited to exhibit index/certifications/signatures','PartIII10–14 completion with explicit unchanged-other-disclosure statement, financial-statements-not-filed statement and body limited to those items+Item15 certifications/signatures'],'necessary_checks':['Validate submitted forms/accession/date/period before filtering','Read both originals via immutable request-ledger binding; issuer/end/reference relationship verified','Read complete amendment, not only note or keyword','Require complete disclosure-scope evidence plus no conflicting financial update; record inherited financial amounts remain original-as-filed','Require every discovered potentially relevant amendment resolved; missing/unknown stays blocked','Financial restatement, explicit debt/equity change, unclear financial scope, unknown original relationship, or changed bytes rejected','No production permission or original Run rewrite follows from no-impact evidence'],'negative_tests':['missing amendment original bytes','same accession with changed amendment bytes','issuer/end/reference mismatch','financial amendment replaces debt/equity facts or PartII Item8','note contains no-update wording but also explicit exception updating financial balances','future other PartIII amendment with unresolved scope','unknown amendment reportDate cannot be filtered away','nonfinancial evidence resolves one amendment but second relevant amendment unresolved'],'warning':'A heuristic searching only PartIII or hyperlink or no-update words is insufficient. If using executable classification rather than scoped reviewed-data determination, conservative structural validation and explicit conflicting evidence rejection required; broad natural-language generalization not established here.'}
(O/'source-review.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n');print(json.dumps({'path':str(O/'source-review.json'),'sha256':sha((O/'source-review.json').read_bytes()),'decisions':[(x['company_id'],x['decision']) for x in out['decisions']]}))
