from pathlib import Path
from decimal import Decimal as D
import xml.etree.ElementTree as E,json,hashlib,datetime
O=Path(__file__).parent
roles={
'Pfizer':{'debt':['DebtCurrent','LongTermDebtNoncurrent'],'check':['LongTermDebtCurrent','OtherShortTermBorrowings','ShorttermDebtGross','LongtermDebtCurrentMaturitiesExcludingNetFairValueAdjustmentsRelatedToHedgingAndPurchaseAccounting','DebtInstrumentUnamortizedDiscountPremiumAndDebtIssuanceCostsNet'],'equity':['StockholdersEquity']},
'Salesforce':{'debt':['LongTermDebt','FinanceLeaseLiability'],'check':['LongTermDebtCurrent','LongTermDebtNoncurrent','FinanceLeaseLiabilityCurrent','FinanceLeaseLiabilityNoncurrent','DebtInstrumentCarryingAmount'],'equity':['StockholdersEquity']},
'Macys':{'debt':['LongTermDebtAndCapitalLeaseObligations','FinanceLeaseLiability'],'check':['DebtCurrent','FinanceLeaseLiabilityCurrent','FinanceLeaseLiabilityNoncurrent','FinanceLeaseLiabilityNonLeaseComponentNoncurrent','DebtInstrumentUnamortizedDiscountPremiumAndDebtIssuanceCostsNet','DebtInstrumentUnamortizedPremiumNoncurrent'],'equity':['StockholdersEquity']},
'Enphase':{'debt':['LongTermDebtCurrent','LongTermDebtNoncurrent'],'check':['LongTermDebt'],'equity':['StockholdersEquity']},
'Southwest':{'debt':['LongTermDebtAndCapitalLeaseObligationsCurrent','LongTermDebtAndCapitalLeaseObligations'],'check':['LongTermDebtAndCapitalLeaseObligationsIncludingCurrentMaturities','DeferredFinanceCostsGross','FinanceLeaseLiability','LongTermDebt'],'equity':['StockholdersEquity']},
'Lumen':{'debt':['DebtAndCapitalLeaseObligations'],'check':['LongTermDebtAndCapitalLeaseObligationsIncludingCurrentMaturities','DebtInstrumentUnamortizedDiscountPremiumNet','DeferredFinanceCostsNet','LongTermDebtAndCapitalLeaseObligationsCurrent','LongTermDebtAndCapitalLeaseObligations','FinanceLeaseAndOtherObligations','FinanceLeaseLiability'],'equity':['StockholdersEquity']},
'Marriott':{'debt':['DebtAndCapitalLeaseObligations'],'check':['CommercialPaperNoncurrent','FinanceLeaseLiability','LongTermDebtAndCapitalLeaseObligationsCurrent','LongTermDebtAndCapitalLeaseObligations'],'equity':['StockholdersEquity']},
'Paramount':{'debt':['DebtAndCapitalLeaseObligations'],'check':['FinanceLeaseLiability','LongTermDebtAndCapitalLeaseObligationsCurrent','LongTermDebtAndCapitalLeaseObligations','DebtInstrumentFaceAmount','DebtInstrumentUnamortizedDiscountPremiumNet'],'equity':['StockholdersEquity']}}
notes={
'Pfizer':['ScheduleOfShortTermDebtTextBlock','ScheduleOfDebtInstrumentsTextBlock','LesseeOperatingLeasesTextBlock'],
'Salesforce':['DebtDisclosureTextBlock','ScheduleOfDebtInstrumentsTextBlock','LesseeLeasesPolicyTextBlock','FinanceLeaseLiabilityMaturityTableTextBlock'],
'Macys':['DebtDisclosureTextBlock','PropertyPlantAndEquipmentAndLeasesOfLesseeDisclosureTextBlock','LesseeLeaseTableTextBlock','FinanceLeaseLiabilityMaturityTableTextBlock'],
'Enphase':['LongTermDebtTextBlock','LesseeLeasesPolicyTextBlock'],
'Southwest':['DebtDisclosureTextBlock','ScheduleOfDebtInstrumentsTextBlock','LesseeOperatingLeasesTextBlock'],
'Lumen':['DebtDisclosureTextBlock','ScheduleOfDebtInstrumentsTextBlock','LesseeFinanceLeasesTextBlock'],
'Marriott':['LongTermDebtTextBlock','ScheduleOfDebtInstrumentsTextBlock','FinanceLeaseLiabilityMaturityTableTextBlock'],
'Paramount':['DebtDisclosureTextBlock','ScheduleOfDebtTableTextBlock','LesseeOperatingLeasesTextBlock']}
judgments={
'Pfizer':{'relationship':'Current carrying borrowings includes current LT debt and separately disclosed other short-term borrowing; noncurrent LT carrying explicitly excludes current portion. Add current carrying plus noncurrent carrying, not current carrying plus current LT again.','included':['Short borrowing157 primarily cash collateral is included under this exact user debt-set decision; not all cash collateral globally.','Borrowings already adjusted to carrying; hedge/purchase adjustments retained.'],'excluded':['Only operating lease balances/costs disclosed in complete lease note and XML; no separately disclosed finance-lease amount found. Do not relabel operating liabilities as financing debt.'],'precision':'LongTermDebtNoncurrent has61641000000 decimals-6 and62000000000 decimals-9 at same context. The precise amount lies within coarse rounding interval; use exact note amount and retain both observations. Real non-overlapping intervals must reject.'},
'Salesforce':{'relationship':'Total borrowing carrying14439 excludes separately recorded finance lease535; add borrowing carrying plus reported finance lease liability.','included':['Finance lease liabilities are in accrued expenses and other liabilities/other noncurrent liabilities, not debt rows;535=275+260.','Nonlease components within reported finance lease remain under user rule.'],'excluded':['Operating lease2737; principal14500 (even though tagged DebtInstrumentCarryingAmount); unused revolving commitments.'],'precision':'Actual precise LongTermDebt14439m and current4000/noncurrent10439 agree; source table makes14500 principal versus14439 carrying explicit despite misleading tag.'},
'Macys':{'relationship':'Bond/note carrying2432 excludes separately reported finance lease13; add them once. Short debt and ABL have no outstanding balance, supported by full financing note.','included':['Finance lease13=2current+11noncurrent; reported finance nonlease component1m remains within13, no subtraction.'],'excluded':['Operating lease3122; available credit/standby letters; principal2441 and separate fair value.'],'precision':'2432 =2441 face less19 discount/costs plus10 acquired premium; all USD millions, same consolidated instant.'},
'Enphase':{'relationship':'Current and noncurrent note carrying amounts exhaust disclosed debt table; complete lease policy explicitly says no finance leases.','included':['632183000 current and572194000 noncurrent, already issuance-cost net.'],'excluded':['Operating leases; marketable commercial paper/bond assets; equity-classified hedge/warrants; expired2025notes.'],'precision':'Debt table thousands, decimals-3. No overlapping coarse competing instant value among used roles.'},
'Southwest':{'relationship':'Current plus noncurrent carrying equals financing pre-cost subtotal less debt issuance costs; finance lease78 is already an explicit debt-table line.','included':['Finance leases78 already included; revolving facility had no outstanding during2025.'],'excluded':['Maturity principal4929 and pre-cost subtotal4919 cannot replace carrying4901.','Operating leases and unused credit limits.'],'precision':'USD millions; same exact context; previously verified4919−18=324+4577. No extra lease add.'},
'Lumen':{'relationship':'Total debt carrying reconciles principal minus net discount and financing costs; finance lease and other obligations220 already debt-table component.','included':['Reported financing obligations including finance lease202 within220 subtotal.'],'excluded':['Operating lease liabilities; principal17815 unadjusted; fair value.'],'precision':'All selected reconciliation terms USD millions/contextc-8;17815−223−151=17441; current88+noncurrent17353; equity negative remains evaluated-null.'},
'Marriott':{'relationship':'Explicit carrying total already includes commercial paper1177, finance lease120 and other borrowing23. Commercial paper classified long-term based on ability and intent to refinance.','included':['Finance lease and short-maturity commercial paper already inside16204; never add again.'],'excluded':['Operating leases; unused4.5bn revolving commitment.'],'precision':'USD millions;16204=1209current+14995noncurrent; equity−3771 remains evaluated-null.'},
'Paramount':{'relationship':'Successor consolidated total carrying already includes finance lease3. No outstanding commercial paper, credit facility or Miramax bank borrowings at2025-12-31.','included':['Senior/junior debt at acquisition-accounting carrying amounts plus finance leases; no switch to predecessor basis.'],'excluded':['Operating leases; face debt14980; fair-value disclosure13200; noncontrolling-inclusive equity.'],'precision':'No synthesized adjusted total: reported13658=433current+13225noncurrent. Unamortized adjustment1.32bn is rounded decimals-7, cannot calculate exact debt from rounded adjustment. Exact total USD millions controls.'}}
reports=[]
for c in roles:
 pre=json.loads((O/(c+'.json')).read_text());p=Path(pre['source']);root=E.parse(p).getroot();ctx={e.get('id'):e for e in root if e.tag.endswith('}context')};units={e.get('id'):e for e in root if e.tag.endswith('}unit')};want={v for values in roles[c].values() for v in values};facts=[];boundnotes=[]
 for e in root:
  tag=e.tag.split('}')[-1];context=ctx.get(e.get('contextRef'))
  if tag in want and context is not None:
   instant=[v.text for v in context.iter() if v.tag.endswith('}instant')];dims=[v for v in context.iter() if v.tag.endswith('}explicitMember') or v.tag.endswith('}typedMember')]
   if instant not in [['2025-12-31'],['2026-01-31']] or dims:continue
   facts.append({'concept':e.tag,'local_concept':tag,'xml_fact_id':e.get('id'),'context_id':e.get('contextRef'),'context_xml':E.tostring(context,encoding='unicode'),'unit_ref':e.get('unitRef'),'unit_xml':E.tostring(units[e.get('unitRef')],encoding='unicode'),'raw_value':e.text,'decimals':e.get('decimals'),'instant':instant[0]})
  if tag in notes[c]:
   text=e.text or '';h=E.fromstring('<root>'+text+'</root>');plain=' '.join(' '.join(h.itertext()).split());boundnotes.append({'concept':e.tag,'xml_fact_id':e.get('id'),'context_id':e.get('contextRef'),'full_note_text_sha256':hashlib.sha256(text.encode()).hexdigest(),'normalized_note_sha256':hashlib.sha256(plain.encode()).hexdigest(),'text_length':len(text),'normalized_text':plain})
 def select(tag):
  candidates=[f for f in facts if f['local_concept']==tag];assert candidates,tag
  best=max(candidates,key=lambda f:int(f['decimals']) if f['decimals']!='INF' else 999)
  bv=D(best['raw_value']);bp=int(best['decimals'])
  for f in candidates:
   v=D(f['raw_value']);precision=int(f['decimals']);half=D(10)**(-precision)/2
   assert v-half<=bv<=v+half,(c,tag,f,best)
  return best
 debtfacts=[select(t) for t in roles[c]['debt']];eq=select('StockholdersEquity');debt=sum(D(f['raw_value']) for f in debtfacts);equity=D(eq['raw_value']);current={'company':c,'source_path':str(p),'source_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'scope':'consolidated exact instant','target_debt_definition':'carrying borrowing + notes/bonds + finance lease including reported combined nonlease components, nonoverlap; operating leases excluded','relation_roles':roles[c],'judgment':judgments[c],'source_facts':facts,'full_related_notes':boundnotes,'audit_computation_only':{'debt':str(debt),'equity':str(equity),'result':'NOT_MEANINGFUL' if equity<=0 else str(debt/equity),'selected_debt_xml_fact_ids':[f['xml_fact_id'] for f in debtfacts],'selected_equity_xml_fact_id':eq['xml_fact_id'],'never_use_review_numbers_as_production_inputs':True}}
 header=Path(str(p)+'.headers.json');assert current['source_sha256'] in header.read_text();current['saved_header_sha256']=hashlib.sha256(header.read_bytes()).hexdigest();reports.append(current)
# These exact values are audit assertions from original documents, not inputs to production.
expected={'Pfizer':'64795000000','Salesforce':'14974000000','Macys':'2445000000','Enphase':'1204377000','Southwest':'4901000000','Lumen':'17441000000','Marriott':'16204000000','Paramount':'13658000000'}
assert all(r['audit_computation_only']['debt']==expected[r['company']] for r in reports)
j={'status':'INDEPENDENT_SOURCE_SCOPE_REVIEW_EIGHT_COORDINATES_SUPPORTED','reviewer':{'task':'/root/debt_reconciliation_review','identity':'independent Codex model source review','human_approval':False},'time':datetime.datetime.now(datetime.timezone.utc).isoformat(),'business_calls':[0,0,0],'scope':'Eight nonbank/nonindustrial-decision coordinates on saved exact2025/2026 fiscal instants; Ford and JPM original source census preserved separately and final special-scope review assigned another agent','checks_executed':['Parse original complete instances and relevant complete note blocks','Match raw sources to saved request headerSHA','Identify context/entity/unit/precision and exact nonoverlap relationships','Decimal sum of independently read raw facts and ratios','Inspect other five originally complete coordinates for omitted finance lease/short borrowings; none newly identified within defined disclosed set'],'not_executed':['Current new implementation validation, native Run or full package replay','Any provider/paid/SEC request','Historical amendment review repeated'],'companies':reports}
(O/'scope-relationships.json').write_text(json.dumps(j,indent=2,ensure_ascii=False)+'\n');print(json.dumps([{ 'company':r['company'],**r['audit_computation_only']} for r in reports],indent=2))
