from pathlib import Path
from decimal import Decimal
import json,hashlib,csv,io,sys,datetime
R=Path('/Users/lyuhongwang/Developer/SEC_metrics');sys.path.insert(0,str(R/'scripts'))
from vnext.canonical import content_hash
from vnext.r5_b06_publication import _code_identity
F=Path('/Users/lyuhongwang/Documents/Codex/2026-09-11/r5-b06-scope-final');O=Path(__file__).parent;read=lambda p:json.loads(p.read_text());sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();prep=read(F/'complete/prepared.json');b=F/'complete/outputs/publications'/prep['publication_id'];m=read(b/'publication_manifest.json');body={k:v for k,v in m.items() if k not in ['record_type','publication_id']};assert 'publication_'+content_hash(value=body)[7:]==m['publication_id']==prep['publication_id'];assert sha(b/'publication_manifest.json')==prep['manifest_sha256'];files={f['path']:f for f in m['files']};checked=[]
def bound(path):
 p=b/path;assert p.stat().st_size==files[path]['size'] and sha(p)==files[path]['sha256'];checked.append({'path':path,**{k:files[path][k] for k in ['size','sha256']}});return p
meta=read(bound('internal/r5_primary.json'));adoption=read(bound('internal/r5_adoption.json'));batch=read(bound('internal/annual_complete_version.json'));matrix=list(csv.DictReader(io.StringIO(bound('metrics_matrix.csv').read_text())));evidence=list(csv.DictReader(io.StringIO(bound('metric_evidence.csv').read_text())))
assert meta==prep['code'] and adoption['coverage']==prep['coverage'];assert content_hash(value={k:v for k,v in adoption.items() if k!='adoption_receipt_id'})==adoption['adoption_receipt_id']==m['annual_adoption_receipt_id'];assert content_hash(value={k:v for k,v in batch.items() if k!='batch_manifest_id'})==batch['batch_manifest_id']==m['batch_manifest_id'];assert meta['implementation_head']=='688fe860fee0ec50403e1cf055617abaae6b6188' and _code_identity(meta['implementation_head'])==meta['implementation_tree'];assert meta['policy']['production_authorized'] is False and adoption['formal_adoption'] is False and m['candidate_status']=='BLOCKED'
code=read(O/'code-review.json');identity=[]
for f in code['reviewed_working_files']:
 assert sha(R/f['path'])==f['sha256'];identity.append(f)
cmd=read(F/'complete-command.json');assert cmd['head']==cmd['head_after']==meta['implementation_head'] and cmd['exit_code']==0 and sha(Path(cmd['log']))==cmd['log_sha256'];assert len(matrix)==328 and len({(r['company'],r['metric_id']) for r in matrix})==328 and len(batch['cumulative_result_bindings'])==250 and batch['inherited_result_count']==240 and batch['selected_result_count']==10
pred=b/'internal/predecessor'/m['previous_publication_id'];assert sha(pred/'publication_manifest.json')==meta['predecessor_manifest_sha256'];old_matrix=list(csv.DictReader(io.StringIO((pred/'metrics_matrix.csv').read_text())));old_ev=list(csv.DictReader(io.StringIO((pred/'metric_evidence.csv').read_text())));unselected=lambda rows:[r for r in rows if r['metric_id']!='B06'];assert unselected(matrix)==unselected(old_matrix) and len(unselected(matrix))==318 and unselected(evidence)==unselected(old_ev)
summaries=[]
for c in adoption['coverage']:
 cid=c['company_id'];rb='internal/annual_snapshot/runs/'+cid;rm=read(bound(rb+'/manifest.json'));records=[json.loads(s) for s in bound(rb+'/records.jsonl').read_text().splitlines()];result=next(r for r in records if r['record_type']=='METRIC_RESULT');assert result==c['result'];refs={r['source_reference_id']:r for r in records if r['record_type']=='SOURCE_REFERENCE'};obs=[r for r in records if r['record_type']=='VERIFIED_OBSERVATION'];public=next(r for r in matrix if r['company']==c['company'] and r['metric_id']=='B06');assert public['status']==c['public_status'] and public['period_end']==c['actual_period']['period_end'] and c['production_permission'] is False
 if cid in ['southwest_airlines','salesforce','macys','enphase_energy','paramount_skydance_paramount_global']:
  n,d={'southwest_airlines':(4901,7981),'salesforce':(14974,59142),'macys':(2445,4860),'enphase_energy':(1204377,1087023),'paramount_skydance_paramount_global':(13658,11693)}[cid];assert Decimal(result['value'])==Decimal(n)/Decimal(d) and c['content_status']=='CONTENT_COMPLETE' and public['status']=='OK'
 if cid in ['lumen_technologies','marriott_international']:assert public['status']=='NOT_MEANINGFUL' and c['result']['value'] is None and Decimal(c['equity'])<0 and c['content_status']=='CONTENT_COMPLETE'
 proof=c['measurement_reconciliation']
 if public['status'] in ['OK','NOT_MEANINGFUL']:
  assert proof['complete'] is True
  for f in proof['calculation_facts']:assert any(o['source_binding'].get('fact_id')==f['fact_id'] and o['value']==f['value'] and all(o['source_binding'].get(k)==v for k,v in f['source_binding'].items()) for o in obs)
  for o in obs:assert refs[o['source_binding']['source_reference_id']]['source_role']=='accession_xbrl'
 if cid in ['ford_motor_company','pfizer','jpmorgan_chase']:
  assert c['content_status']=='CONTENT_GAPS_REMAIN' and public['status']=='NEEDS_REVIEW' and public['value']=='' and result['publication']=='WITHHELD' and c['debt'] is None and proof['complete'] is False and obs==[]
 if cid=='pfizer':assert c['proven_debt_subtotal']=='64795000000' and 'FINANCE_LEASE_COMPLETENESS_NOT_ESTABLISHED' in c['blockers']
 if cid=='jpmorgan_chase':
  assert c['proven_debt_subtotal']=='970329000000' and proof['model']['diagnostic_only'] is True
  assert sum(Decimal(f['value']) for f in proof['components'].values())==Decimal('970329000000');assert 'BANK_FINANCE_LEASE_COMPLETENESS_NOT_ESTABLISHED' in c['blockers']
 summaries.append({'company_id':cid,'public_status':public['status'],'debt':c['debt'],'proven_debt_subtotal':c['proven_debt_subtotal'],'equity':c['equity'],'value':result['value'],'blockers':c['blockers'],'run_id':rm['run_id'],'result_id':result['result_id'],'native_observation_count':len(obs)})
statuscounts={s:sum(c['public_status']==s for c in adoption['coverage']) for s in ['OK','NOT_MEANINGFUL','NEEDS_REVIEW']};assert statuscounts=={'OK':5,'NOT_MEANINGFUL':2,'NEEDS_REVIEW':3}
ci=read(F/'ci-implementation-proof.json');assert ci['head']==meta['implementation_head'] and sha(F/'ci-implementation.log')==ci['log_sha256']
logs=[{'path':'complete-command.json','exit_code':0,'head':cmd['head'],'log_sha256':cmd['log_sha256']}];pending=[]
for kind in ['material','cold','old-candidate']:
 p=F/(kind+'-command.json')
 if not p.exists():pending.append(kind);continue
 v=read(p);assert sha(Path(v['log']))==v['log_sha256'];logs.append({'path':p.name,'exit_code':v['exit_code'],'head':v['head'],'log_sha256':v['log_sha256'],'performed_by':'parent; read and hash-checked by this reviewer'})
x={'status':'PASS_BOUNDED_FINAL_SCOPE_PACKAGE_INCREMENT','reviewer':'independent Codex subtask /root/debt_reconciliation_review; not human approval','time':datetime.datetime.now(datetime.timezone.utc).isoformat(),'implementation_head':meta['implementation_head'],'implementation_tree':meta['implementation_tree'],'publication_id':m['publication_id'],'manifest_file_sha256':sha(b/'publication_manifest.json'),'adoption_object_id':adoption['adoption_receipt_id'],'batch_object_id':batch['batch_manifest_id'],'personally_executed':['Key25file hash/size checks; recomputed manifest/adoption/batch content IDs','Actual prepare command/log and package code identity verified against Git object; prior reviewed code hashes unchanged','All10 stored native Result records aligned with coverage/public rows; actual accepted Observations align with originalXML calculation facts','5correct numeric results,2nonpositive-equity results,3incomplete-set withholds; Pfizer64795 and bank970329 remain diagnostic only','All318 unselected rows and their evidence equal actual embedded predecessor, no added duplicate keys'],'read_execution_records':logs,'read_ci_evidence':ci,'reused':['Prior independent8source audit with explicit Pfizer-completeness supplementary correction','Independent source/scope code review and11scope tests,6negative checks','Small oldv1/v2 native graph reads from code-review; not repeated here','Bank/industrial special originalsource review by other independent agent'],'not_executed':['No repeat full publication validator or all native Run graphs; actual record/identity comparison only','No repeat material/fault/cold execution; read parent execution outputs','No production operation or provider/SEC call'],'remaining_code_or_wrong_acceptance_blockers':[],'conditions_for_merge':'No unresolved code or erroneous-result acceptance blocker found within this independent increment. Remaining economic completeness gaps are explicitly withheld, not implementation success claims. Parent must complete required final execution logs/protection/CI and head comparison before applying user conditional merge authority.','pending_execution_records':pending,'coverage_status_counts':statuscounts,'coverage':summaries,'coordinate_count':250,'public_rows':328,'unchanged_public_rows':318,'business_calls':[0,0,0],'production_authorized':False,'reviewed_code_binding':identity,'checked_files':checked,'reporting_caveat':'Bank diagnostic coverage current/noncurrent labels are abstract placeholders: long-term statement debt includes current maturities. Amount sums four disjoint reported rows once. diagnostic_only and completeFalse prohibit Result; a future accepted bank model needs precise reported-group categories rather than literal maturity partition labels.'};(O/'final-package-review.json').write_text(json.dumps(x,indent=2,ensure_ascii=False)+'\n');print(x['status'],statuscounts,'pending',pending)
