import csv,hashlib,json,subprocess,sys,tempfile,time
from pathlib import Path
base=Path(tempfile.mkdtemp(prefix='ford-auditor-company-',dir='/Users/lyuhongwang/.local/state/sec_metrics/issue47-development-evidence'));state=base/'state';source='/Users/lyuhongwang/.codex/worktrees/7e99/SEC_metrics-issue47-company-verified-source-20261006/source-inputs'
args=['run','--company','ford_motor_company','--period','fiscal-years','--fiscal-year-start','2022','--fiscal-year-end','2022','--metric','C04','--source-root',source,'--work-dir',str(state),'--output-dir',str(base/'runs')]
def protected():return {str(p.relative_to(state)):hashlib.sha256(p.read_bytes()).hexdigest() for p in state.rglob('*') if p.is_file() and ('/results/' in str(p) or p.name in ['company-task.json','current-result.json','completed-check.json'])}
def invoke(name,args,forbid=False):
 code='import json,sys\nfrom unittest.mock import patch\nfrom tools.vnext_company import main\n'
 if forbid:code+='from vnext import historical_auditor_case as cases,calculator\na=cases.prepare_historical_auditor_year_case.__code__;b=calculator.calculate_metric.__code__;c=calculator.calculate_observation_metric.__code__\ndef guard(frame,event,arg):\n if event=="call" and (frame.f_code is a or frame.f_code is b or frame.f_code is c):raise AssertionError("Stable C04 cannot recalculate")\nsys.setprofile(guard)\n'
 code+='with patch("socket.socket.connect",side_effect=AssertionError("No network")):\n raise SystemExit(main(json.loads(sys.argv[1])))'
 t=time.monotonic();p=subprocess.run([sys.executable,'-B','-c',code,json.dumps(args)],capture_output=True,text=True);secs=time.monotonic()-t;(base/(name+'.stdout')).write_text(p.stdout);(base/(name+'.stderr')).write_text(p.stderr);print(name,p.returncode,round(secs,3),flush=True);assert p.returncode==0 and not p.stderr,(p.returncode,p.stdout,p.stderr)
 return {'seconds':secs,'exit_code':p.returncode,'arguments':args},json.loads(p.stdout)
first,r=invoke('fresh-selected-company',args);assert len(r['metrics'])==1 and r['metrics'][0]['calculation_performed'];root=Path(r['metrics'][0]['result_root']);a=json.load((root/'input-assessments.json').open())['assessments']['historical_auditor'];assert a['names_differ'] is False and not a['matched_item_4_01_claim_ids'] and len(a['event_forms'])==4 and a['reason_code']=='PASS';records=[json.loads(l) for l in (root/'records.jsonl').read_text().splitlines()];result=next(x for x in records if x['record_type']=='METRIC_RESULT');assert result['value']=='0' and result['unit']=='flag';post=protected()
repeat,r=invoke('forbidden-case-calculation-repeat',args,True);assert r['metrics'][0]['status']=='NO_SOURCE_CONTENT_CHANGE' and not r['metrics'][0]['calculation_performed'];assert protected()==post
read,v=invoke('independent-current-export',['results','--company','ford_motor_company','--state-root',str(state),'--output-root',str(base/'read')],True);assert protected()==post;rows=list(csv.DictReader((base/'read/metrics_matrix.csv').open()));assert len(rows)==1;row=rows[0];assert row['value']=='0' and row['unit']=='flag' and row['fiscal_year']=='2022' and row['period_start']=='2022-01-01' and row['period_end']=='2022-12-31' and row['cik']=='37996'
receipt={'code_commit':subprocess.check_output(['git','rev-parse','HEAD'],text=True).strip(),'uncommitted_shared_receiving_tree':True,'first':first,'repeat':repeat,'read':read,'row':row,'state_root':str(state),'output_root':str(base),'protected_files':len(post),'complete_selection':a,'record_count':len(records),'new_calls':[0,0,0],'reference_not_input':True}
Path('work/auditor-company/actual-company.json').write_text(json.dumps(receipt,indent=2)+'\n');print('PASS same selected company/source/core/save/reuse/read/CSV C04',flush=True)
