import json,time,hashlib,sys
from pathlib import Path
import task_contract as t
from sec_http import write_immutable_bytes
from vnext.native_unit_index import evidence_json_bytes
base=Path("/Users/lyuhongwang/.local/state/sec_metrics/issue28-development-evidence");h=Path("docs/evidence/issue28_continuous/d03-native-context-input-trial-20261004");rows=[];start=time.monotonic()
for company,file,digest in [("marriott",base/"d03-complete-six-responses-20261004/source.json","5c4aae9c6a1f671d348b0e41c3eefb526a3710a4c9d463f77f7e39d54f909b5b"),("jpm",base/"d03-jpm-positive-20261004/source.json","11189144bf0bff60c8995086f9fb2bfa253a38a1206d557a059b9c771f8486a9")]:
 raw=file.read_bytes();assert hashlib.sha256(raw).hexdigest()==digest;s=json.loads(raw);plan=t.scan_plan(s,digest,grouping_input_target=150000)
 summary={"company":company,"source_sha256":digest,"original_unit_count":len(s["units"]),"first_scan_count":plan["first_scan_count"],"design_total_ceiling":plan["total_request_ceiling"],"max_context_tokens":max(x["measure"]["context_tokens"] for x in plan["tasks"]),"tasks":[{"owner_ids":x["payload"]["responsibility_unit_ids"],"request_sha256":x["request_sha256"],"input_tokens":x["measure"]["input_tokens"]} for x in plan["tasks"]]};rows.append(summary);print(json.dumps({k:v for k,v in summary.items() if k!="tasks"}),flush=True)
 if company=="marriott":
  owner="sha256:c54e0429db2d3eb364dbd0c69e432e81c9941e495ab069f713fee32ec16b7666";task=next(x for x in plan["tasks"] if owner in x["payload"]["responsibility_unit_ids"]);out=base/"d03-native-context-input-trial-20261004";write_immutable_bytes(path=out/"scan-request-headroom.json",content=task["request_body"])
  fixture={"reviewed_unit_ids":task["payload"]["responsibility_unit_ids"],"findings":[],"scope_current_involvement":"UNRESOLVED","unresolved":["RECORDED resource preflight, not a model answer"],"scan_complete":False,"context_requests":[{"anchor":{"unit_id":owner,"kind":"NATIVE_FACT","source_index":507},"target":{"kind":"XML_ELEMENT_ID","element_id":"f-497-1"}}]};r=evidence_json_bytes(fixture);follow=t.prepare_followup(s,digest,task,r,hashlib.sha256(r).hexdigest());sample={"request_path":str(out/"scan-request-headroom.json"),"owner_ids":task["payload"]["responsibility_unit_ids"],"request_sha256":task["request_sha256"],"measure":task["measure"],"recorded_followup_status":follow["status"],"recorded_followup_measure":follow.get("measure"),"context_packet":follow["parsed"]["located_context"],"recorded_not_model":True};(h/"headroom-sample.json").write_bytes(evidence_json_bytes(sample));print(json.dumps({"sample_owners":len(sample["owner_ids"]),"sample_context":task["measure"]["context_tokens"],"followup":follow["status"],"followup_context":follow.get("measure",{}).get("context_tokens")}),flush=True)
report={"grouping_input_target_not_service_limit":150000,"samples":rows,"seconds":format(time.monotonic()-start,".3f"),"complete_company_ready":False,"business_calls":[0,0,0]};(h/"headroom-plan.json").write_bytes(evidence_json_bytes(report))
